### ISSUE TITLE
Search queries do not respond outside of title page

### ISSUE THREAD

**Issue by ComradeDiamond** [densumesh/debatev-frontend#1]
If there are no filters in the advanced filter section (outside of the title page), the search query does not respond and says that some input button is null (probably due to some DOM fetch operation returning null). I can't pinpoint exactly what it is though because it's minified.

Here's an img of the problem
<img src="https://i.imgur.com/sKCyoVg.png" />

**Comment by densumesh** [comment]
it should be working now, i forgot to change the variable name after i copy pasted from another file.
